import { Project, ApkRelease, Skill, Technology, TechnologyCategory, Platform, WebsiteContent, SocialLink, WebsiteSettings, AdminUser } from '../types';
import { generateAppScreenshot } from '../assets/mockScreenshots';

export const initialPlatforms: Platform[] = [
  {
    id: 'plat-android',
    name: 'Android App',
    slug: 'android-app',
    icon: 'android',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'plat-ios',
    name: 'iOS App',
    slug: 'ios-app',
    icon: 'apple',
    display_order: 2,
    is_active: true,
  },
  {
    id: 'plat-web-app',
    name: 'Web Application',
    slug: 'web-app',
    icon: 'globe',
    display_order: 3,
    is_active: true,
  },
  {
    id: 'plat-website',
    name: 'Website',
    slug: 'website',
    icon: 'globe',
    display_order: 4,
    is_active: true,
  },
  {
    id: 'plat-desktop',
    name: 'Desktop Application',
    slug: 'desktop-app',
    icon: 'monitor',
    display_order: 5,
    is_active: true,
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-rentora',
    title: 'Rentora',
    slug: 'rentora',
    subtitle: 'Property & Tenant Management App',
    shortDescription: 'Property & Tenant Management',
    fullDescription:
      'Rentora helps landlords and property owners manage their properties, tenants and billing easily. Track rent, generate bills, handle payments and more — all in one place.',
    category: 'mobile',
    icon: 'home',
    iconBg: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    version: 'v1.4.0',
    apkSize: '18 MB',
    lastUpdated: '26 Sep 2026',
    featured: true,
    playStoreEnabled: true,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.gotop.rentora',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/rentora-v1.4.0.apk',
    platforms: ['Android App'],
    technologies: ['Flutter', 'Firebase', 'Cloudinary', 'PDF Generator'],
    features: [
      'Property Management (Add / Edit / Delete)',
      'Tenant Management (Add / Edit / Delete)',
      'Bill Generation (Electricity / Water / Other Charges)',
      'Payment Tracking (Partial / Full / Due)',
      'PDF Bill Download (On Demand)',
      'Reports & Analytics',
    ],
    screenshots: [
      generateAppScreenshot('Rentora', '#10b981', 'Dashboard', 'dashboard'),
      generateAppScreenshot('Rentora', '#10b981', 'Property Info', 'detail'),
      generateAppScreenshot('Rentora', '#10b981', 'Tenant Directory', 'list'),
      generateAppScreenshot('Rentora', '#10b981', 'Billing Engine', 'analytics'),
      generateAppScreenshot('Rentora', '#10b981', 'Payment Receipts', 'detail'),
      generateAppScreenshot('Rentora', '#10b981', 'Monthly Reports', 'dashboard'),
    ],
  },
  {
    id: 'proj-musiqd',
    title: 'MusiqD',
    slug: 'musiqd',
    subtitle: 'Music Streaming (Private)',
    shortDescription: 'Music Streaming (Private)',
    fullDescription:
      'High-fidelity lossless music streaming platform with background audio service, offline local caching, dynamic playlist creation, and timed lyric synchronization.',
    category: 'mobile',
    icon: 'music',
    iconBg: 'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
    version: 'v1.2.0',
    apkSize: '16 MB',
    lastUpdated: '18 Sep 2026',
    featured: true,
    playStoreEnabled: false,
    playStoreUrl: '',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/musiqd-v1.2.0.apk',
    platforms: ['Android App', 'iOS App'],
    technologies: ['Flutter', 'Supabase', 'Just Audio', 'Riverpod'],
    features: [
      'Lossless FLAC & 320kbps Audio Streaming',
      'Dynamic Waveform Visualizer & Lyrics Sync',
      'Offline Smart Audio Caching',
      'Custom 10-Band Equalizer & Bass Boost',
      'Cloud Playlist Synchronization',
    ],
    screenshots: [
      generateAppScreenshot('MusiqD', '#ec4899', 'Now Playing', 'media'),
      generateAppScreenshot('MusiqD', '#ec4899', 'Playlists & Mixes', 'list'),
      generateAppScreenshot('MusiqD', '#ec4899', 'Lossless Stream', 'dashboard'),
      generateAppScreenshot('MusiqD', '#ec4899', 'Equalizer & Bass', 'detail'),
    ],
  },
  {
    id: 'proj-infinityflix',
    title: 'InfinityFlix',
    slug: 'infinityflix',
    subtitle: 'Movies & Web Series (OTT)',
    shortDescription: 'Movies & Web Series (OTT)',
    fullDescription:
      'A comprehensive entertainment discovery and streaming companion. Explore trending films, watch official high-definition trailers, manage personal watchlists, and enjoy seamless subtitle support.',
    category: 'mobile',
    icon: 'film',
    iconBg: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    version: 'v2.1.0',
    apkSize: '15 MB',
    lastUpdated: '12 Sep 2026',
    featured: true,
    playStoreEnabled: true,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.gotop.infinityflix',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/infinityflix-v2.1.0.apk',
    platforms: ['Android App', 'iOS App', 'Web Application'],
    technologies: ['Flutter', 'TMDB', 'Dio', 'Bloc'],
    features: [
      'Rich TMDB API integration with 500,000+ titles',
      'HD trailer streaming with hardware acceleration',
      'Personalized watchlist & favorites synchronization',
      'Multi-language audio & subtitle switcher',
      'Deep cast, director, and recommendations explorer',
    ],
    screenshots: [
      generateAppScreenshot('InfinityFlix', '#8b5cf6', 'Discover Movies', 'media'),
      generateAppScreenshot('InfinityFlix', '#8b5cf6', 'Movie Synopsis', 'detail'),
      generateAppScreenshot('InfinityFlix', '#8b5cf6', 'Trailer Cinema', 'dashboard'),
      generateAppScreenshot('InfinityFlix', '#8b5cf6', 'User Watchlist', 'list'),
    ],
  },
  {
    id: 'proj-quickdrop',
    title: 'QuickDrop',
    slug: 'quickdrop',
    subtitle: 'File Sharing (Quick & Secure)',
    shortDescription: 'File Sharing (Quick & Secure)',
    fullDescription:
      'Peer-to-peer ultra-fast cross-platform file transfer tool using local Wi-Fi hotspots and WebRTC encryption. Transfer files, photos, videos, and folders without consuming mobile internet.',
    category: 'mobile',
    icon: 'send',
    iconBg: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    version: 'v1.1.0',
    apkSize: '10 MB',
    lastUpdated: '05 Sep 2026',
    featured: true,
    playStoreEnabled: true,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.gotop.quickdrop',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/quickdrop-v1.1.0.apk',
    platforms: ['Android App'],
    technologies: ['Flutter', 'Firebase', 'WebSockets', 'Go'],
    features: [
      'Zero cellular data usage peer-to-peer Wi-Fi transfer',
      'Speeds up to 45 MB/s transfer rate',
      'End-to-end local network encryption',
      'Bulk file & folder sharing',
      'QR code pairing for instantaneous connections',
    ],
    screenshots: [
      generateAppScreenshot('QuickDrop', '#06b6d4', 'Radar Transfer', 'dashboard'),
      generateAppScreenshot('QuickDrop', '#06b6d4', 'Device Scanner', 'detail'),
      generateAppScreenshot('QuickDrop', '#06b6d4', 'Transfer Queue', 'list'),
    ],
  },
  {
    id: 'proj-yuva',
    title: 'Yuva (WhatsApp Clone)',
    slug: 'yuva',
    subtitle: 'Chat & Call App',
    shortDescription: 'Chat & Call App',
    fullDescription:
      'Full-featured real-time messaging application with end-to-end encryption, status updates, voice notes, group channels, and high-definition audio/video calling.',
    category: 'mobile',
    icon: 'message-circle',
    iconBg: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
    version: 'v1.0.0',
    apkSize: '14 MB',
    lastUpdated: '01 Sep 2026',
    featured: false,
    playStoreEnabled: false,
    playStoreUrl: '',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/yuva-v1.0.0.apk',
    platforms: ['Android App', 'iOS App'],
    technologies: ['Flutter', 'WebSockets', 'Firebase', 'Node.js'],
    features: [
      'Real-time messaging with typing & read receipts',
      'Voice & video calls powered by WebRTC',
      '24-Hour ephemeral Stories/Status updates',
      'Group chats with admin controls',
      'Local media vault with PIN protection',
    ],
    screenshots: [
      generateAppScreenshot('Yuva', '#22c55e', 'Chat Stream', 'chat'),
      generateAppScreenshot('Yuva', '#22c55e', 'Voice Call UI', 'detail'),
      generateAppScreenshot('Yuva', '#22c55e', 'Stories Feed', 'list'),
    ],
  },
  {
    id: 'proj-earnspin',
    title: 'Earn Spin',
    slug: 'earnspin',
    subtitle: 'Rewards & Earning App',
    shortDescription: 'Rewards & Earning App',
    fullDescription:
      'Engaging gamified rewards platform featuring lucky wheel spins, daily scratch cards, trivia quizzes, and redeemable digital currency with instant payouts.',
    category: 'mobile',
    icon: 'disc',
    iconBg: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    version: 'v1.0.0',
    apkSize: '8 MB',
    lastUpdated: '28 Aug 2026',
    featured: false,
    playStoreEnabled: true,
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.gotop.earnspin',
    apkDownloadEnabled: true,
    apkDownloadUrl: 'https://r2.gotop-technologies.com/apks/earnspin-v1.0.0.apk',
    platforms: ['Android App'],
    technologies: ['Flutter', 'AdMob', 'Express', 'MongoDB'],
    features: [
      'Interactive 3D fortune wheel spin physics',
      'Daily reward streaks & scratch cards',
      'AdMob rewarded video ads integration',
      'Instant UPI and PayPal payouts',
      'Anti-fraud cheat detection engine',
    ],
    screenshots: [
      generateAppScreenshot('Earn Spin', '#f97316', 'Lucky Wheel', 'dashboard'),
      generateAppScreenshot('Earn Spin', '#f97316', 'Wallet & Balance', 'detail'),
      generateAppScreenshot('Earn Spin', '#f97316', 'Leaderboard', 'list'),
    ],
  },
  {
    id: 'proj-portfolio',
    title: 'Portfolio Website',
    slug: 'portfolio-website',
    subtitle: 'Modern Developer Portfolio & Showcase',
    shortDescription: 'Modern Developer Portfolio & Showcase',
    fullDescription:
      'Modern, highly responsive developer showcase website crafted with a futuristic dark theme, neon glow accents, interactive project showcases, APK releases engine, and full admin capabilities.',
    category: 'web',
    icon: 'home',
    iconBg: 'linear-gradient(135deg, #38bdf8 0%, #6366f1 100%)',
    version: 'v2.5.0',
    apkSize: 'N/A (Web)',
    lastUpdated: '01 Oct 2026',
    featured: false,
    playStoreEnabled: false,
    playStoreUrl: '',
    apkDownloadEnabled: false,
    apkDownloadUrl: '',
    platforms: ['Website'],
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Supabase'],
    features: [
      'Futuristic dark neon aesthetic with glassmorphism',
      'Dynamic project filtering and live search',
      'Dedicated official brand skills explorer',
      'Admin control suite with Supabase backend',
    ],
    screenshots: [
      generateAppScreenshot('Portfolio', '#38bdf8', 'Hero Showcase', 'dashboard'),
      generateAppScreenshot('Portfolio', '#38bdf8', 'Projects View', 'list'),
    ],
  },
  {
    id: 'proj-admin-dashboard',
    title: 'Admin Dashboard',
    slug: 'admin-dashboard',
    subtitle: 'Content & Application Management Suite',
    shortDescription: 'Content & Application Management Suite',
    fullDescription:
      'Complete administrative management system providing real-time analytics, project publishing, APK distribution logs, and full database CRUD controls.',
    category: 'web',
    icon: 'disc',
    iconBg: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
    version: 'v2.0.0',
    apkSize: 'N/A (Web)',
    lastUpdated: '01 Oct 2026',
    featured: false,
    playStoreEnabled: false,
    playStoreUrl: '',
    apkDownloadEnabled: false,
    apkDownloadUrl: '',
    platforms: ['Web Application'],
    technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'ChartJS'],
    features: [
      'Role-based access control & authentication',
      'Interactive visitor & download telemetry',
      'Full APK release and direct link manager',
      'Platform and technology classification',
    ],
    screenshots: [
      generateAppScreenshot('Admin Suite', '#a855f7', 'Analytics Matrix', 'analytics'),
      generateAppScreenshot('Admin Suite', '#a855f7', 'Control Console', 'dashboard'),
    ],
  },
];

export const initialApkReleases: ApkRelease[] = [
  {
    id: 'rel-rentora-140',
    projectId: 'proj-rentora',
    projectName: 'Rentora',
    projectIcon: 'home',
    version: 'v1.4.0',
    size: '18 MB',
    releaseDate: '26 Sep 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/rentora-v1.4.0.apk',
    releaseNotes: 'Added PDF bill generation, offline sync improvements, and tenant rent reminders.',
    isLatest: true,
    downloadsCount: 4210,
  },
  {
    id: 'rel-musiqd-120',
    projectId: 'proj-musiqd',
    projectName: 'MusiqD',
    projectIcon: 'music',
    version: 'v1.2.0',
    size: '16 MB',
    releaseDate: '18 Sep 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/musiqd-v1.2.0.apk',
    releaseNotes: 'Introduced 10-band equalizer, synced timed lyrics, and reduced battery drain.',
    isLatest: true,
    downloadsCount: 3120,
  },
  {
    id: 'rel-infinityflix-210',
    projectId: 'proj-infinityflix',
    projectName: 'InfinityFlix',
    projectIcon: 'film',
    version: 'v2.1.0',
    size: '15 MB',
    releaseDate: '12 Sep 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/infinityflix-v2.1.0.apk',
    releaseNotes: '4K trailer playback, TMDB trending filters, and custom watchlist sharing.',
    isLatest: true,
    downloadsCount: 2890,
  },
  {
    id: 'rel-quickdrop-110',
    projectId: 'proj-quickdrop',
    projectName: 'QuickDrop',
    projectIcon: 'send',
    version: 'v1.1.0',
    size: '10 MB',
    releaseDate: '05 Sep 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/quickdrop-v1.1.0.apk',
    releaseNotes: 'Speed optimizations up to 45 MB/s, directory transfer bug fixes.',
    isLatest: true,
    downloadsCount: 1450,
  },
  {
    id: 'rel-yuva-100',
    projectId: 'proj-yuva',
    projectName: 'Yuva',
    projectIcon: 'message-circle',
    version: 'v1.0.0',
    size: '14 MB',
    releaseDate: '01 Sep 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/yuva-v1.0.0.apk',
    releaseNotes: 'Initial public beta with end-to-end encrypted chats and audio calls.',
    isLatest: true,
    downloadsCount: 520,
  },
  {
    id: 'rel-earnspin-100',
    projectId: 'proj-earnspin',
    projectName: 'Earn Spin',
    projectIcon: 'disc',
    version: 'v1.0.0',
    size: '8 MB',
    releaseDate: '28 Aug 2026',
    downloadUrl: 'https://r2.gotop-technologies.com/apks/earnspin-v1.0.0.apk',
    releaseNotes: 'Initial release with daily rewards, spin wheel, and AdMob integration.',
    isLatest: true,
    downloadsCount: 260,
  },
];

export const initialTechnologyCategories: TechnologyCategory[] = [
  { id: 'cat-mobile', name: 'Mobile Development', display_order: 1 },
  { id: 'cat-web', name: 'Web Development', display_order: 2 },
  { id: 'cat-backend', name: 'Backend & Database', display_order: 3 },
  { id: 'cat-lang', name: 'Programming Languages', display_order: 4 },
  { id: 'cat-tools', name: 'Development Tools', display_order: 5 },
  { id: 'cat-design', name: 'Design & Productivity', display_order: 6 },
  { id: 'cat-devops', name: 'DevOps / Infrastructure', display_order: 7 },
];

export const initialTechnologies: Technology[] = [
  // Mobile Development
  {
    id: 'tech-flutter',
    name: 'Flutter',
    logo_url: '/logos/flutter.svg',
    category: 'Mobile Development',
    description: 'Mobile App Development',
    display_order: 1,
    is_active: true,
    featured_on_home: true,
    proficiency: 95,
  },
  {
    id: 'tech-react-native',
    name: 'React Native',
    logo_url: '/logos/react-native.svg',
    category: 'Mobile Development',
    description: 'Cross-Platform Framework',
    display_order: 2,
    is_active: true,
    featured_on_home: true,
    proficiency: 88,
  },

  // Web Development
  {
    id: 'tech-react',
    name: 'React',
    logo_url: '/logos/react.svg',
    category: 'Web Development',
    description: 'Frontend UI Library',
    display_order: 3,
    is_active: true,
    featured_on_home: true,
    proficiency: 92,
  },
  {
    id: 'tech-tailwind',
    name: 'Tailwind CSS',
    logo_url: '/logos/tailwind.svg',
    category: 'Web Development',
    description: 'Modern Styling System',
    display_order: 4,
    is_active: true,
    featured_on_home: false,
    proficiency: 90,
  },

  // Backend & Database
  {
    id: 'tech-firebase',
    name: 'Firebase',
    logo_url: '/logos/firebase.svg',
    category: 'Backend & Database',
    description: 'Cloud Auth & Realtime DB',
    display_order: 5,
    is_active: true,
    featured_on_home: true,
    proficiency: 90,
  },
  {
    id: 'tech-supabase',
    name: 'Supabase',
    logo_url: '/logos/supabase.svg',
    category: 'Backend & Database',
    description: 'PostgreSQL & Realtime Backend',
    display_order: 6,
    is_active: true,
    featured_on_home: true,
    proficiency: 94,
  },
  {
    id: 'tech-node',
    name: 'Node.js',
    logo_url: '/logos/nodejs.svg',
    category: 'Backend & Database',
    description: 'Runtime & REST APIs',
    display_order: 7,
    is_active: true,
    featured_on_home: true,
    proficiency: 86,
  },
  {
    id: 'tech-mongo',
    name: 'MongoDB',
    logo_url: '/logos/mongodb.svg',
    category: 'Backend & Database',
    description: 'NoSQL Document Store',
    display_order: 8,
    is_active: true,
    featured_on_home: false,
    proficiency: 82,
  },

  // Programming Languages
  {
    id: 'tech-dart',
    name: 'Dart',
    logo_url: '/logos/dart.svg',
    category: 'Programming Languages',
    description: 'Client-Optimized Language',
    display_order: 9,
    is_active: true,
    featured_on_home: false,
    proficiency: 92,
  },
  {
    id: 'tech-javascript',
    name: 'JavaScript',
    logo_url: '/logos/javascript.svg',
    category: 'Programming Languages',
    description: 'Modern ES6+ Logic',
    display_order: 10,
    is_active: true,
    featured_on_home: true,
    proficiency: 95,
  },
  {
    id: 'tech-typescript',
    name: 'TypeScript',
    logo_url: '/logos/typescript.svg',
    category: 'Programming Languages',
    description: 'Strict Type-Safe Code',
    display_order: 11,
    is_active: true,
    featured_on_home: true,
    proficiency: 90,
  },
  {
    id: 'tech-python',
    name: 'Python',
    logo_url: '/logos/python.svg',
    category: 'Programming Languages',
    description: 'Scripting & Automation',
    display_order: 12,
    is_active: true,
    featured_on_home: false,
    proficiency: 84,
  },

  // Development Tools
  {
    id: 'tech-git',
    name: 'Git',
    logo_url: '/logos/git.svg',
    category: 'Development Tools',
    description: 'Version Control System',
    display_order: 13,
    is_active: true,
    featured_on_home: true,
    proficiency: 94,
  },
  {
    id: 'tech-github',
    name: 'GitHub',
    logo_url: '/logos/github.svg',
    category: 'Development Tools',
    description: 'Code Repository & CI/CD',
    display_order: 14,
    is_active: true,
    featured_on_home: true,
    proficiency: 92,
  },
  {
    id: 'tech-vscode',
    name: 'VS Code',
    logo_url: '/logos/vscode.svg',
    category: 'Development Tools',
    description: 'Primary Development IDE',
    display_order: 15,
    is_active: true,
    featured_on_home: true,
    proficiency: 96,
  },
  {
    id: 'tech-androidstudio',
    name: 'Android Studio',
    logo_url: '/logos/androidstudio.svg',
    category: 'Development Tools',
    description: 'Native Android Tools & Gradle',
    display_order: 16,
    is_active: true,
    featured_on_home: true,
    proficiency: 88,
  },
  {
    id: 'tech-postman',
    name: 'Postman',
    logo_url: '/logos/postman.svg',
    category: 'Development Tools',
    description: 'API Design & Testing',
    display_order: 17,
    is_active: true,
    featured_on_home: false,
    proficiency: 89,
  },

  // Design & Productivity
  {
    id: 'tech-figma',
    name: 'Figma',
    logo_url: '/logos/figma.svg',
    category: 'Design & Productivity',
    description: 'UI/UX Interface Prototyping',
    display_order: 18,
    is_active: true,
    featured_on_home: true,
    proficiency: 90,
  },
  {
    id: 'tech-canva',
    name: 'Canva',
    logo_url: '/logos/canva.svg',
    category: 'Design & Productivity',
    description: 'Visual Assets & Branding',
    display_order: 19,
    is_active: true,
    featured_on_home: false,
    proficiency: 86,
  },

  // DevOps / Infrastructure
  {
    id: 'tech-docker',
    name: 'Docker',
    logo_url: '/logos/docker.svg',
    category: 'DevOps / Infrastructure',
    description: 'Containerization & Environments',
    display_order: 20,
    is_active: true,
    featured_on_home: false,
    proficiency: 82,
  },
  {
    id: 'tech-linux',
    name: 'Linux',
    logo_url: '/logos/linux.svg',
    category: 'DevOps / Infrastructure',
    description: 'Server Administration & CLI',
    display_order: 21,
    is_active: true,
    featured_on_home: false,
    proficiency: 85,
  },
  {
    id: 'tech-cloudflare',
    name: 'Cloudflare',
    logo_url: '/logos/cloudflare.svg',
    category: 'DevOps / Infrastructure',
    description: 'Edge CDN & R2 APK Storage',
    display_order: 22,
    is_active: true,
    featured_on_home: false,
    proficiency: 88,
  },
];

export const initialSkills: Skill[] = initialTechnologies;

export const initialWebsiteContent: WebsiteContent = {
  hero: {
    greeting: "Hi, I'm",
    developerTitle: 'GoTop Developer',
    subtitle: 'I Build Modern Mobile Apps',
    techStack: 'Flutter | React Native | Web | Backend',
    description:
      "I'm a passionate developer who loves turning ideas into powerful mobile applications. Check out my projects and feel free to get in touch!",
    primaryBtnText: 'View Projects',
    secondaryBtnText: 'Contact Me',
  },
  stats: {
    appsDeveloped: '6+',
    appsDevelopedLabel: 'Apps Developed',
    yearsExperience: '2+',
    yearsExperienceLabel: 'Years Experience',
    passion: '100%',
    passionLabel: 'Passion',
  },
  about: {
    badge: 'About Me',
    heading: 'Turning Ideas into Real Apps',
    subheading: 'Full-Stack Mobile & Web Specialist',
    description:
      "I'm a Mobile App Developer with a strong passion for building useful and beautiful applications. I specialize in Flutter, React Native, Firebase, Supabase and modern web technologies.",
    highlights: [
      { id: 'hl-1', title: 'Problem Solver', icon: 'target' },
      { id: 'hl-2', title: 'Clean & Scalable Code', icon: 'zap' },
      { id: 'hl-3', title: 'User Focused', icon: 'user' },
      { id: 'hl-4', title: 'Always Learning', icon: 'book-open' },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    signatureText: "Let's Build Something Great!",
    authorName: 'Rahul',
  },
  contact: {
    heading: 'Get In Touch',
    subheading: "Let's Work Together",
    description:
      "Have a project in mind or just want to say hi? Feel free to reach out, I'd love to hear from you!",
    email: 'contact@gotop-technologies.com',
    phone: '+91 98765 43210',
    location: 'India',
  },
  footer: {
    brandName: 'GoTop',
    tagline: 'Build • Innovate • Grow',
    copyrightText: '© 2026 GoTop Technologies. All rights reserved.',
    madeWithText: 'Made with ❤️ by GoTop',
  },
};

export const initialSocialLinks: SocialLink[] = [
  { id: 'soc-github', platform: 'GitHub', label: 'GitHub', url: 'https://github.com/gotop-dev', icon: 'github' },
  { id: 'soc-linkedin', platform: 'LinkedIn', label: 'LinkedIn', url: 'https://linkedin.com/in/gotop-dev', icon: 'linkedin' },
  { id: 'soc-youtube', platform: 'YouTube', label: 'YouTube', url: 'https://youtube.com/@gotop-dev', icon: 'youtube' },
  { id: 'soc-telegram', platform: 'Telegram', label: 'Telegram', url: 'https://t.me/gotop_dev', icon: 'send' },
  { id: 'soc-twitter', platform: 'Twitter', label: 'Twitter / X', url: 'https://x.com/gotop_dev', icon: 'twitter' },
];

export const initialWebsiteSettings: WebsiteSettings = {
  websiteName: 'GoTop Technologies',
  logoText: 'GoTop',
  favicon: '/favicon.svg',
  seoTitle: 'GoTop Developer - Mobile & Full-Stack Engineer',
  seoDescription:
    'Portfolio of GoTop Developer. Building high-performance Flutter, React Native, and full-stack web applications.',
  socialPreviewImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
  themePreference: 'dark',
  supabaseUrl: '',
  supabaseAnonKey: '',
  r2Endpoint: 'https://r2.gotop-technologies.com',
};

export const defaultAdminUser: AdminUser = {
  id: 'admin-1',
  email: 'admin@gotop.dev',
  name: 'GoTop Admin',
  role: 'admin',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
};
